name: shoppingannuity
favicon: null
layout_spectrum: 0.12660798826254904
typography_spectrum: 0.5199836657848209
title: Convert your existing spending into earning.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9ce0ed'
    - '#b9b9b9'
    - '#7d7d7d'
    - '#202020'
  brandStrength: 1
  lightness: 0.8335547568276525
  saturation: 0.45437813899479806
  rhythmicContrast: 0.5
purpose: []
